// TomatoASIKCOM.idl : Tomato.ASIK.COM 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 产生类型库(TomatoASIKCOM.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(a817e7a2-43fa-11d0-9e44-00aa00b6770a),
	dual,	
	pointer_default(unique)
]
interface IComponentRegistrar : IDispatch
{
	[id(1)]	HRESULT Attach([in] BSTR bstrPath);
	[id(2)]	HRESULT RegisterAll();
	[id(3)]	HRESULT UnregisterAll();
	[id(4)]	HRESULT GetComponents([out] SAFEARRAY(BSTR)* pbstrCLSIDs, [out] SAFEARRAY(BSTR)* pbstrDescriptions);
	[id(5)]	HRESULT RegisterComponent([in] BSTR bstrCLSID);
	[id(6)] HRESULT UnregisterComponent([in] BSTR bstrCLSID);
};

[
	object,
	uuid(3E2D02BC-A21E-463A-87EA-85BE51A211AA),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IMFIOProvider : IDispatch{
	[id(1), helpstring("初始化")] HRESULT Initialize();
	[id(2), helpstring("加载文件")] HRESULT LoadFile([in] LPCWSTR fileName, [out] DWORD* bufferSize);
	[id(3), helpstring("读取所有采样")] HRESULT ReadAllSamples([in, out] SAFEARRAY(BYTE) buffer);
};
[
	uuid(CB5A590D-0E69-47B5-A78C-09889E691D5E),
	version(1.0),
	custom(a817e7a1-43fa-11d0-9e44-00aa00b6770a,"{EB4B2598-E756-445C-B19A-EADB7DE8A6F6}"),
	helpstring("Tomato ASIK 1.0 Type Library")
]
library TomatoASIKCOMLib
{
	importlib("stdole2.tlb");
	[
		uuid(EB4B2598-E756-445C-B19A-EADB7DE8A6F6)		
	]
	coclass CompReg
	{
		[default] interface IComponentRegistrar;
	};
	[
		uuid(B70B76E3-EFD2-4F0A-AAE5-7FD5E71FB0FF)		
	]
	dispinterface _IMFIOProviderEvents
	{
		properties:
		methods:
	};
	[
		uuid(D6A0DE03-0132-4C5C-B5A1-A24ABB9E9B29)		
	]
	coclass MFIOProvider
	{
		[default] interface IMFIOProvider;
		[default, source] dispinterface _IMFIOProviderEvents;
	};
};

